version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp-image
    container_name: myapp-container
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./app:/app
